#!/bin/bash

echo "🚀 Backend AWS Deployment Options"
echo "================================="
echo ""
echo "Your FastAPI backend can be deployed to AWS in several ways:"
echo ""

echo "📋 OPTION 1: AWS Lambda + Function URL (RECOMMENDED - Easiest)"
echo "   ✅ Pros: Serverless, auto-scaling, pay-per-request, simple setup"
echo "   ✅ Setup: One Terraform file, built-in CORS, direct HTTPS URL"
echo "   ⚡ Cost: ~\$0.20 per 1M requests (very cheap for development)"
echo "   🚀 Deploy: terraform apply (uses lambda-simple.tf)"
echo ""

echo "📋 OPTION 2: AWS Lambda + API Gateway (More features)"
echo "   ✅ Pros: Advanced routing, request validation, rate limiting"
echo "   ⚠️  Setup: More complex, requires API Gateway configuration"
echo "   🚀 Deploy: terraform apply (uses lambda-api.tf)"
echo ""

echo "📋 OPTION 3: AWS ECS Fargate (Container-based)"
echo "   ✅ Pros: Full Docker support, better for complex apps"
echo "   ⚠️  Cost: Always running (~\$15-30/month minimum)"
echo "   🚀 Deploy: Requires Docker setup + ECS configuration"
echo ""

echo "💡 RECOMMENDATION: Start with Option 1 (Lambda + Function URL)"
echo "   - Easiest to set up and maintain"
echo "   - Perfect for your current application size"
echo "   - Can easily upgrade to API Gateway later if needed"
echo ""

echo "🛠️ NEXT STEPS:"
echo ""
echo "1️⃣ Choose your deployment option"
echo ""
echo "2️⃣ For Lambda deployment (Option 1 - Recommended):"
echo "   a) Install dependencies: pip install mangum boto3"
echo "   b) Run: ./deploy-backend-aws.sh"
echo "   c) This will:"
echo "      • Package your FastAPI app for Lambda"
echo "      • Deploy with Terraform"
echo "      • Update frontend to use AWS API URL"
echo "      • Redeploy frontend to S3"
echo ""
echo "3️⃣ Alternative - Manual Lambda deployment:"
echo "   a) cd terraform"
echo "   b) Uncomment lambda-simple.tf resources"
echo "   c) terraform plan"
echo "   d) terraform apply"
echo "   e) Update frontend/.env.production with the output URL"
echo "   f) Rebuild and redeploy frontend"
echo ""

echo "🔧 Current Status:"
echo "   ✅ Infrastructure: Ready (S3 buckets deployed)"
echo "   ✅ Frontend: Deployed to AWS S3"
echo "   ⏳ Backend: Running locally (ready for AWS deployment)"
echo ""

echo "📊 Expected Results After Backend Deployment:"
echo "   🌐 Frontend: http://quickbite-blue.s3-website-us-east-1.amazonaws.com"
echo "   🔧 Backend: https://[random-id].lambda-url.us-east-1.on.aws/"
echo "   📚 API Docs: https://[random-id].lambda-url.us-east-1.on.aws/docs"
echo ""

echo "💰 Estimated AWS Costs (Lambda):"
echo "   Development usage: \$0-5/month"
echo "   Production usage: \$5-20/month (depending on traffic)"
echo ""

echo "🎯 Ready to deploy backend to AWS? Run:"
echo "   ./deploy-backend-aws.sh"
